### ISSUE TITLE
Accessing TL throws segmentation fault

### ISSUE THREAD

**Issue by MakisH** [precice/athlet-adapter#15]
Trying to access TL throws a segmentation fault without much more information (at least with ATHLET built in Release mode). Some of the commented-out lines in https://github.com/precice/athlet-adapter/commit/b44ea8123dc245a6fcbad19613022aae489334ad causes this issue and most probably:

```fortran
_refVar( CDPR_scope, "tl",  TL )
```

**Comment by kwwong333** [comment]
Is this a ATHLET related problem? If you can provide the error log in the out file, I may can help to track down the issue.

**Comment by MakisH** [comment]
Unfortunately there is not much more output available:

(in the tutorial repository, after commenting-out `_refVar( CDPR_scope, "tl",  TL )` and ` write(*,101) TL
`)

<details><summary>Click for details...</summary>

```
$ ./runPipe1 
FORTRES: setting plugin path
 >> /(removed)/ATHLET_Release/bin/athlet.Release.gfortran/plugin
FORTRES: setting plugin path
 >> /(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin/libprecice_adapter.Release.gfortran.so' ... loaded, try symbol execute_c_: ok
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin/libhdf5_writer.Release.gfortran.so' ... loaded, try symbol execute_c_: ok
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin/libfde.release.64.gfortran.so' ... loaded, try symbol execute_c_: not found
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin/libhdf5_f90cstub.so' ... loaded, try symbol execute_c_: not found
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin/libprecice.so' ... loaded, try symbol execute_c_: not found
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/athlet.Release.gfortran/../plugin/libhdf5.so' ... loaded, try symbol execute_c_: not found
  
  ATHLET: Start ...
  SIEDTA: Formatting Input
  SIEDTA: Input Formatted
  
  AIN0  : Start of Processing Input Data
  ...   : Scan of Plugin Folder for Enabled Plugins: Passed
  ...   : Input Scan for Allocations Started
  ...   : Input Scan for Allocations Finished
  ...   : Start Allocations of Basic Arrays
  ...   : Basic Arrays Allocated
  ...   : Simulation Preconditions: Passed
  ...   : TOPOLOGY Data Reading: Passed
  
  AIN1  : Continue Processing Input Data
  ...   : OBJECT Data Reading: Passed
  ...   : TFOs Concatenation: Passed
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/plugin_gfortran/libhdf5_writer.Release.gfortran.so.1.9465' ... loaded, try symbol : ok
FORTRES: check plugin '/(removed)/ATHLET_Release/bin/plugin_gfortran/libprecice_adapter.Release.gfortran.so.1' ... loaded, try symbol : ok
  ...   : GCSM Data Reading: Passed
  ...   : All Input Data Reading: Passed
  ...   : Initialization After Input: Passed
  AIN1  : End of Processing Input Data
  
  ASTART: Start of Steady State Calculation
  ASTART: End of Steady State Calculation
  
  Caught SegmentationFault: handle_segv
```
</details>

Unfortunately I cannot run ATHLET in Debug mode due to a separate (not adapter-related) issue.

**Comment by kwwong333** [comment]
Can you tell me the step to reproduce the error, i.e. which branch should be i pull and what is the step to run your case? I can try to debug it myself with your adapter. 

For the debugger error, I suppose you are referring to the error in ATRANS.
I think the fix for the debug mode error is just to add a line, `TG0TRN =-1.D10`, at the end of the file of ccac.f90 (where you can see some variables are predefined there). 

The TG0TRN is simply a zero transient related variable, however, it is not pre-defined if the simulation does not include a ZEROTRANS card. However, I can't repeat the error with the ifort compiler. I understand that may raise a floating point error for gfortran. So, you can try this to see if that solve the issue. Is that possible for you to compile the source code of ATHLET? Otherwise, you may need to wait until the external git repository has been set up.

**Comment by MakisH** [comment]
> Can you tell me the step to reproduce the error, i.e. which branch should be i pull and what is the step to run your case? I can try to debug it myself with your adapter.

I am working on the SCCS branch, currently on revision 9465 (last changed 9393), and building with gfortran 9.3.0. You can directly get the adapter branch [debug-15](https://github.com/precice/athlet-adapter/tree/debug-15).

The documentation for building the adapter is in the [wiki of this repository](https://github.com/precice/athlet-adapter/wiki/Building).

___

> For the debugger error, I suppose you are referring to the error in ATRANS.

Exactly, as discussed via email (where the debugger reaches an invalid value of `TG0TRN`).

> I think the fix for the debug mode error is just to add a line, TG0TRN =-1.D10, at the end of the file of ccac.f90 (where you can see some variables are predefined there).

Thank you, this fixed this exception, but I get a similar one a bit later, where `H0T11B` is NaN (only defined in `atrans.f90` as equal to `H0`). I guess that the Intel compiler sets undefined variables to a convenient value (which sounds dangerous). Note that this you can simply reproduce with the bundled Sample1 of ATHLET, no need for any preCICE-related code.

> The TG0TRN is simply a zero transient related variable, however, it is not pre-defined if the input deck does not include a ZEROTRANS card.

Reading the manual I assume then that I don't need a `ZEROTRANS`, so it is probably just a bug.

> Is that possible for you to compile the source code of ATHLET?

Yes, I can compile the source, but only the older version I currently have.

Thank you very much for your help! :smiley:

**Comment by kwwong333** [comment]
> Thank you, this fixed this exception, but I get a similar one a bit later, where H0T11B is NaN (only defined in atrans.f90 as equal to H0). I guess that the Intel compiler sets undefined variables to a convenient value (which sounds dangerous). Note that this you can simply reproduce with the bundled Sample1 of ATHLET, no need for any preCICE-related code.

For the further error in atrans.f90, I guess you can predefined the variable by adding the following line in atrans after line 574,
```
574 DO I = 1,6
575     H0T11B = -1.0D10 
```
This should avoid the problem of NaN for this variable. Please let me know if you met further error in this subroutine.

**Comment by MakisH** [comment]
This also solved the second exception and now the Sample1 runs fine in Debug mode.

My case from the `develop` branch now runs normally in Debug mode. Trying now to debug this issue (TL, branch `debug-15`), I get the following segfault:

```
  ASTART: Start of Steady State Calculation
  ASTART: End of Steady State Calculation
  

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6326620 in string_ne_charstring_c (lhs=<error reading variable: Cannot access memory at address 0x510000cf>, rhs=..., _rhs=2) at ./src/string_impl.f90:587
587	    res = _ptr(lhs) /= rhs
```

**Comment by kwwong333** [comment]
I saw in `precice_adapter.f90` for the cdtf module, you did the following,
```
      ! Bind pointer CDTF_scope to the state_scope/cdtf
      CDTF_scope  => getScope( state_scope, "cdtf" )
```
Is it possible that you missed the code to bind the pointer to module CDPR? 
```
      ! Bind pointer CDTF_scope to the state_scope/cdtf
      CDPR_scope  => getScope( state_scope, "cdpr" )
```

**Comment by MakisH** [comment]
> Is it possible that you missed the code to bind the pointer to module CDPR (at around line 73)?

Yes! This was it, I was a bit lost in the scopes. Thank you again very much. :smiley:
