### ISSUE TITLE
Adapter does not adapt the timestep of ATHLET

### ISSUE THREAD

**Issue by MakisH** [precice/athlet-adapter#9]
Similarly to #8, after `advance(dt)` we get a new value for `dt`, which we then need to use to set the time step size of the next outer-loop FEBE time step. For this, we actually need to get the minimum of the two time step sizes.

**Comment by MakisH** [comment]
The adapter now adapts the `h0next`. When calling `initialize()`:
https://github.com/precice/athlet-adapter/blob/5e8701ad758ec4d78ad1f6f8a9ea6df6841c6da4/precice_adapter.f90#L127-L139

When calling `advance()`:
https://github.com/precice/athlet-adapter/blob/5e8701ad758ec4d78ad1f6f8a9ea6df6841c6da4/precice_adapter.f90#L207-L217

We still need to confirm if this is the right time step size to adapt, but a first log seems reasonable:

```
  ASTART: Start of Steady State Calculation
  ASTART: End of Steady State Calculation
  
---[adapter] ===== ATHLET preCICE adapter: Starting... =====
---[adapter] Participant name: SolverOne                                         
---[adapter] Mesh name: MeshOne                                           
---[adapter] Interface location: outlet                                            
---[adapter] Creating preCICE...
---[precice]  This is preCICE version 2.0.1
---[precice]  Revision info: v2.0.1
---[precice]  Configuring preCICE with configuration: "precice-config.xml"
---[precice]  Setting up master communication to coupling partner/s
---[precice]  Masters are connected
---[precice]  Setting up preliminary slaves communication to coupling partner/s
---[precice]  Prepare partition for mesh MeshOne
---[precice]  Gather mesh MeshOne
---[precice]  Send global mesh MeshOne
---[precice]  Setting up slaves communication to coupling partner/s
---[precice]  Slaves are connected
---[precice]  it 1 of 1 | dt# 1 | t 0 of 10 | dt 0.05 | max dt 0.05 | ongoing yes | dt complete no | 
---[adapter]      0.0500000: Time step size limit imposed by preCICE after initialize()
---[adapter]      0.0000000: Time step size of ATHLET (h0next)
---[precice]  initializeData is skipped since no data has to be initialized
---[adapter] =================================================

  ATRANS: Start of Transient Calculation
  ...   : Initialization of Transient Calculation: Passed
  ATRANS: Start of Transient Loop
 T= 2.00000000000D-05 H0= 2.00000D-05 DT= 2.00000D-05 IZS=      1 LM=     1 LFK= 34 CPU=      0 H0N:   NO LIMIT. DT:   NO LIMIT.
---[adapter] ===== ATHLET preCICE adapter: Executing... =====
---[adapter] Writing Pressure
---[adapter]      0.0500000: Time step size limit imposed by preCICE before new advance()
---[adapter]      0.0002000: Time step size of ATHLET before new advance() (h0next)
---[precice]  it 1 of 1 | dt# 1 | t 0.0002 of 10 | dt 0.05 | max dt 0.0498 | ongoing yes | dt complete no | 
---[adapter] ================================================
 
 T= 2.20000000000D-04 H0= 2.00000D-04 DT= 2.00000D-04 IZS=      2 LM=     2 LFK= 22 CPU=      0 H0N:   NO LIMIT. DT:   NO LIMIT.
---[adapter] ===== ATHLET preCICE adapter: Executing... =====
---[adapter] Writing Pressure
---[adapter]      0.0498000: Time step size limit imposed by preCICE before new advance()
---[adapter]      0.0020000: Time step size of ATHLET before new advance() (h0next)
---[precice]  it 1 of 1 | dt# 1 | t 0.0022 of 10 | dt 0.05 | max dt 0.0478 | ongoing yes | dt complete no | 
---[adapter] ================================================
 
 T= 1.00000000000D-03 H0= 7.80000D-04 DT= 7.80000D-04 IZS=      3 LM=     2 LFK=  5 CPU=      0 H0N:   NO LIMIT. DT:   NO LIMIT.
---[adapter] ===== ATHLET preCICE adapter: Executing... =====
---[adapter] Writing Pressure
---[adapter]      0.0478000: Time step size limit imposed by preCICE before new advance()
---[adapter]      0.0078000: Time step size of ATHLET before new advance() (h0next)
---[precice]  it 1 of 1 | dt# 1 | t 0.01 of 10 | dt 0.05 | max dt 0.04 | ongoing yes | dt complete no | 
---[adapter] ================================================
```

The sequence of events in every loop iteration is roughly the following:
1. solve the current time step
2. write data
3. set the next iteration's step size and give it to preCICE
4. advance
5. read data

I am not completely sure if we should be setting `h0next` or `h0` (or `dt`), so I would prefer to leave this open for now.

**Comment by uekerman** [comment]
There is a slight mistake here:
> 3. set the next iteration's step size and give it to preCICE

preCICE needs the timestep size of **this** timestep, not the next one. After calling `advance` the next timestep size of ATHLET can be computed (if ATHLET has already computed its dt).

**Comment by MakisH** [comment]
Indeed, I got confused here for a moment. So, normally we would need to do:

1. Compute the solver_dt
2. Set solver_dt as the minimum of {solver_dt, precice_dt}
3. Solve
4. Write
5. Advance (with current solver_dt and get **next** precice_dt)
6. Read

But we currently cannot (or don't know how to) inject code between 1&3.

This only holds only **if the time step size of the solver is indeed computed at 1**. If the time step size **of the next iteration** is computed after "solve" (and before the hook we have), then we could do this:

1. Solve
2. Compute the **next** solver_dt
3. Write
4. Advance (with current solver_dt and get **next** precice_dt)
5. Read
6. Set the **next** solver_dt as the minimum of {solver_dt, precice_dt}

**Comment by uekerman** [comment]
Yes, correct, but sounds quite complicated. Does ATHLET really do it that way? 
Alternative would be to ask for a hook between 1&3 above. At least in the long run.

**Comment by MakisH** [comment]
> I am not completely sure if we should be setting `h0next` or `h0` (or `dt`), so I would prefer to leave this open for now.

It is probably that there are multiple `h0next` suggestions that all together lead to (a smaller) `dt`. We could try directly setting `dt` for now.

**Comment by MakisH** [comment]
- Let's try with `HMAX` instead
- `HMAX` should stay fixed, therefore we don't need the additional hook

I will try and report.

**Comment by MakisH** [comment]
I hope I now fixed everything in https://github.com/precice/athlet-adapter/commit/b672d22aa076fee4f4fd0705e438e53c9fd1354d (and the next two commits, which mainly addressed #13).

The mechanism is the following:
- `initialize`: give the initial `hmax_athlet_initial`, get a suggested `dt_limit` from preCICE
- `advance`: give the current `dt`, get a suggested `dt_limit` from preCICE
- after both, apply `hmax_athlet = min(hmax_athlet_initial, dt_limit)`

Notes:
1. We set `hmax`, which is the limit, not the exact time step size. This way, ATHLET can still perform a smaller time step, if needed.
2. In every iteration, we read again the current time step size `dt` and give it to preCICE. Therefore, ATHLET can indeed do a smaller time step, if needed.
3. We always compare with the initial `hmax` (which should be user-defined), otherwise ATHLET will always perform very small time steps, even if it is not required by preCICE (since we overwrite `hmax` in every iteration).

Here is what is happening around `advance()`:
https://github.com/precice/athlet-adapter/blob/a4798be412cb525702365baba4faa2af7ca3f67b/precice_adapter.f90#L263-L280

Example output (including `initialize` and `advance`):
[dt.log](https://github.com/precice/athlet-adapter/files/5027480/dt.log)

```
---[adapter] ===== ATHLET preCICE adapter: Starting... =====
---[adapter] Participant name: SolverOne                                         
---[adapter] Mesh name: MeshOne                                           
---[adapter] Interface location: outlet                                            
---[adapter] Assuming Outlet at cell index:    20
---[adapter] Creating preCICE...
---[precice]  This is preCICE version 2.0.2
---[precice]  Revision info: v2.0.2
---[precice]  Configuring preCICE with configuration: "precice-config.xml"
---[adapter]      0.0000000: Current time step size of ATHLET (pointer to dt)
---[adapter]      0.1000000: Next time step size limit before initialize(dt_limit) - not a pointer, preset as hmax
---[adapter]      0.1000000: Next max allowed time step size of ATHLET (pointer to hmax)
---[precice]  Setting up master communication to coupling partner/s
---[precice]  Masters are connected
---[precice]  Setting up preliminary slaves communication to coupling partner/s
---[precice]  Prepare partition for mesh MeshOne
---[precice]  Gather mesh MeshOne
---[precice]  Send global mesh MeshOne
---[precice]  Setting up slaves communication to coupling partner/s
---[precice]  Slaves are connected
---[precice]  it 1 of 1 | dt# 1 | t 0 of 0.15 | dt 0.05 | max dt 0.05 | ongoing yes | dt complete no | 
---[adapter]      0.0000000: Time step size of ATHLET (pointer to dt)
---[adapter]      0.0500000: Time step size limit imposed by preCICE after initialize(dt_limit)
---[adapter]      0.1000000: Current max allowed time step size of ATHLET (pointer to hmax)
---[adapter]      0.1000000: Initial max allowed time step size of ATHLET (backup of hmax)
---[adapter]      0.0500000: --> Next max allowed time step size of ATHLET (pointer to hmax)
---[precice]  initializeData is skipped since no data has to be initialized
---[adapter] =================================================

  ATRANS: Start of Transient Calculation
  ...   : Initialization of Transient Calculation: Passed
  ATRANS: Start of Transient Loop
 T= 2.00000000000D-05 H0= 2.00000D-05 DT= 2.00000D-05 IZS=      1 LM=     1 LFK= 34 CPU=      0 H0N:   NO LIMIT. DT:   NO LIMIT.
---[adapter] ===== ATHLET preCICE adapter: Executing... =====
---[adapter]      0.0000000: Current time
---[adapter]      0.0000200: Time step size of ATHLET (pointer to dt)
---[adapter]      0.0500000: Previous preCICE time step size limit - before advance(dt_limit)
---[adapter]      0.0500000: Max allowed time step size of ATHLET (pointer to hmax)
---[precice]  it 1 of 1 | dt# 1 | t 2e-05 of 0.15 | dt 0.05 | max dt 0.04998 | ongoing yes | dt complete no | 
---[adapter]      0.0000200: Current time step size of ATHLET (pointer to dt)
---[adapter]      0.0499800: Next preCICE time step size limit - after advance(dt_limit)
---[adapter]      0.0500000: Current max allowed time step size of ATHLET (pointer to hmax)
---[adapter]      0.1000000: Initial max allowed time step size of ATHLET (backup of hmax)
---[adapter]      0.0499800: --> Next max allowed time step size of ATHLET (pointer to hmax)
---[adapter] ================================================
 
 T= 2.20000000000D-04 H0= 2.00000D-04 DT= 2.00000D-04 IZS=      2 LM=     2 LFK= 22 CPU=      0 H0N:   NO LIMIT. DT:   NO LIMIT.
---[adapter] ===== ATHLET preCICE adapter: Executing... =====
---[adapter]      0.0000200: Current time
---[adapter]      0.0002000: Time step size of ATHLET (pointer to dt)
---[adapter]      0.0499800: Previous preCICE time step size limit - before advance(dt_limit)
---[adapter]      0.0499800: Max allowed time step size of ATHLET (pointer to hmax)
---[precice]  it 1 of 1 | dt# 1 | t 0.00022 of 0.15 | dt 0.05 | max dt 0.04978 | ongoing yes | dt complete no | 
---[adapter]      0.0002000: Current time step size of ATHLET (pointer to dt)
---[adapter]      0.0497800: Next preCICE time step size limit - after advance(dt_limit)
---[adapter]      0.0499800: Current max allowed time step size of ATHLET (pointer to hmax)
---[adapter]      0.1000000: Initial max allowed time step size of ATHLET (backup of hmax)
---[adapter]      0.0497800: --> Next max allowed time step size of ATHLET (pointer to hmax)
---[adapter] ================================================
```

Questions:
- @uekerman: Does this mechanism make sense now?
- @FWey: Is the main edit (`T=... H0=...`) printed in the beginning or at the end of a loop? If in the beginning, everything should be fine.
- @FWey: Now the adapter overwrites `HMAX` to some value. If another component wants to set a smaller time step size, when will this happen? If it happens in the beginning of the next time step, everything should be fine. Otherwise, I should add a check that only overwrites it if it is smaller.

**Comment by FWey** [comment]
The main edit T=... H0=.. is printed after the FEBE-Solver finished. So more or less at the end of a time step.

The value for HMAX for the maximum time step size won't be changed by another component. But it could be prescirbed by a GCSM-Signal defined by the user. This would affect HMAX at the very beginning of a time step. But other components could, if they realize that the current time step size is to large, restart the time step again with a smaller step size.

**Comment by MakisH** [comment]
This seems to be ok for now, let's close it and open a separate issue if needed, in the future.

**Comment by uekerman** [comment]
Looks good in general. One small odd thing

> T= 1.00000000000D-03 H0= 7.80000D-04 DT= 7.80000D-04 IZS=      3 LM=     2 LFK=  5 CPU=      0 H0N:   NO LIMIT. DT:   NO LIMIT.
---[adapter] ===== ATHLET preCICE adapter: Executing... =====
---[adapter]      0.0002200: Current time

It seems like the "current time" is delayed by one timestep. It does not match the "T" above, which is the correct value.
This value is not needed by adapter, but still it is odd that the value it could access is wrong.
